###
GET http://localhost:3568/api/data

###
GET http://localhost:3568/

###
POST http://localhost:3568/api/data
Content-Type: application/json

{
    "name": "Elena"
}

###

DELETE http://localhost:3568/api/data